### ISSUE TITLE
Implementation Interfaces

### ISSUE THREAD

**Issue by graywolf336** [graywolf336/temporary-rocketlets-ts-definition#1]
Hey @mrsimpson I'm going to be using this repository for a little while until things are ready to be moved into Rocket.Chat itself then we'll move underneath the Rocket.Chat organization.

My question is, what should the interfaces be named which the Rocketlets will implement when they implement that said feature? Should it be `IPreMessageSentListener` or just `IPreMessageSent`? And then if they're handling incoming webhooks, `IWebHookListener`?

**Comment by mrsimpson** [comment]
@graywolf336 better not ask me for naming things. I'm quite ... special about that...
I'd call the interfaces with a suffix (like "listener") only if I can think of other meaningful suffixes. In this case, where an interface describes handling of an event, I'd call them like the event as this is the main purpose, so "IPreMesageSent". 
I'd expect it to have methods like "validate", "modify" (maybe even an explicit "enrich"), each with a signature which allows them to read some data from RocketChat and with manipulating accessors for the latter one or two. 
IPostMessageSent could have something like "filter" and "execute". 
With respect to the Webhook handler, I'd call it either "IWebhookHandler" or "...Provider" (such as it is common in other worlds). 
Does that make sense to you?

**Comment by graywolf336** [comment]
> I'd expect it to have methods like "validate", "modify" (maybe even an explicit "enrich"), each with a signature which allows them to read some data from RocketChat and with manipulating accessors for the latter one or two.

Can you expound on what you mean by this? As I don't follow 100%

> With respect to the Webhook handler, I'd call it either "IWebhookHandler" or "...Provider" (such as it is common in other worlds).

Ah yes, those are way better choices than what I had in mind. I think the `Provider` is an excellant choice for the Webhook as implementing this interface means the Rocketlet will provide an endpoint for people call. :+1:

**Comment by graywolf336** [comment]
Future reference see: #2
