### ISSUE TITLE
Accessor Pagination

### ISSUE THREAD

**Issue by graywolf336** [graywolf336/temporary-rocketlets-ts-definition#3]
On the accessors which query and have the potential to return a lot of data, I feel there should be some sort of pagination or limit.

The `IRoomRead` there's a method `getMessages(roomId: string): Array<IMessage>` and one would assume that calling this would return all of the messages inside of the room. When that method is called on large channels, such as demo's general channel, there are thousands of messages to return.

How should this be handled?

**Comment by graywolf336** [comment]
First option would be the first thing that comes to most minds and that's pagination.

So, the method would be something like `getMessages(roomId: string, pagination: IPagination): IPaginationResult<IMessage>` and the `IPagination` would contain the `count` and `offset` (or some other name) and the `IPaginationResult<IMessage>` would return those values and the total count plus have an array of the items for that "page".

**Comment by graywolf336** [comment]
Second option would be something which operates as an Iterator and on each `next()` goes out and gets it from the database.

https://basarat.gitbooks.io/typescript/docs/iterators.html

**Comment by graywolf336** [comment]
@mrsimpson Just to ping you for visibility

**Comment by graywolf336** [comment]
With the iterator it would change the getMessages to `getMessages(roomId: string): IIterator<IMessage>;`. The iterator interface definition would be as simple as the following:

```ts
import { IIteratorResult } from './IIteratorResult';

export interface IIterator<T> {
    next(skip: number): IIteratorResult<T>;
    [Symbol.iterator](): IIterator<T>;
}
```

**Comment by mrsimpson** [comment]
@graywolf336 good point!

- I was about to propose the paginator, which I use previously. However, you have to return the pagination information in addition to the actual target entity. In JS, where functions have only one return value, this means that an object representing the result with multiple components needs to be created.
- returning an iterator makes consumption a bit more complex, but on the other hand it is comparable to a cursor. What about returning something like a cursor, but having the pagesize as parameter?

**Comment by mrsimpson** [comment]
Sorry, there was an overlap (I'm on a train), but basically similar ideas: https://github.com/mrsimpson/temporary-rocketlets-ts-definition/commit/30b8a5d68228d805b1608791466b5a6fd620e9bb 

what do you need `[Symbol.iterator](): IIterator<T>;` for

**Comment by graywolf336** [comment]
* Right, so that would mean we would need a `IPaginationResult` like I suggested above with `count`, `offset`, and `total` along with the actual results.
* The iterator/cursor with a pagesize would be a different approach.

As for the `[Symbol.iterator](): IIterator<T>;` that's a JavaScript specific item to allow the iterator to be used with `for(let v of iterator) { console.log(v) }`

**Comment by graywolf336** [comment]
So, if we did the page size for the iterators it would have:

```ts
export interface IIteratorResult<T> {
    done: boolean;
    values: Array<T>;
}
```

And:

```ts
export interface IRoomRead {
    getMessages(roomId: string, pageSize?: number): IIterator<IMessage>;

    getMembers(roomId: string, pageSize?: number): IIterator<IUser>;
}
```

**Comment by graywolf336** [comment]
If going the pagination result, not the iterator, then the example result interface could be something like:

```ts
export interface IPaginationResult<T> {
    count: number;
    offset: number;
    total: number;
    values: Array<T>;
}
```

**Comment by mrsimpson** [comment]
I'd appreciate if "next" returned the values directly, not another wrapper

**Comment by graywolf336** [comment]
For future record, this discussion has moved to #4
